
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 250

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'lib/sensu-plugins-elasticsearch/elasticsearch-query.rb'

# TODO: come cleanup the code that uses this once we figure out what we want to use
Lint/UriEscapeUnescape:
  Enabled: false

# TODO: switch from `DateTime` to `Time` or `Date`
Style/DateTime:
  Enabled: false
